# Document classification

In [1]:
import nltk
import re
#nltk.download('stopwords')
import pickle
#from nltk.corpus import stopwords

In [2]:
def explode(df, lst_cols, fill_value='', preserve_index=False):
    # make sure `lst_cols` is list-alike
    if (lst_cols is not None
        and len(lst_cols) > 0
        and not isinstance(lst_cols, (list, tuple, np.ndarray, pd.Series))):
        lst_cols = [lst_cols]
    # all columns except `lst_cols`
    idx_cols = df.columns.difference(lst_cols)
    # calculate lengths of lists
    lens = df[lst_cols[0]].str.len()
    # preserve original index values    
    idx = np.repeat(df.index.values, lens)
    # create "exploded" DF
    res = (pd.DataFrame({
                col:np.repeat(df[col].values, lens)
                for col in idx_cols},
                index=idx)
             .assign(**{col:np.concatenate(df.loc[lens>0, col].values)
                            for col in lst_cols}))
    # append those rows that have empty lists
    if (lens == 0).any():
        # at least one list in cells is empty
        res = (res.append(df.loc[lens==0, idx_cols], sort=False)
                  .fillna(fill_value))
    # revert the original index order
    res = res.sort_index()
    # reset index if requested
    if not preserve_index:        
        res = res.reset_index(drop=True)
    return res

In [3]:
from sklearn.datasets import load_files
my_data=load_files(r'C:\ML Training Docs\New folder\data_final')
X,y = my_data.data, my_data.target

In [4]:
import pandas as pd
import numpy as np
df=pd.DataFrame({'filenames':[my_data.filenames],'target':[my_data.target]})
df=explode(df,['filenames','target'],fill_value='',preserve_index=True)
df['target']=df['target'].replace([0,1,2,3,4],['3rd Party Expert','GMC','MDU Invoices','Solicitor Contacts','NHSLA'])
df.to_csv(r'C:\ML Training Docs\New folder\data_final\data_final.csv',index=False)
df

filenames              target
0   C:\ML Training Docs\New folder\data_final\MDU ...        MDU Invoices
0   C:\ML Training Docs\New folder\data_final\MDU_...  Solicitor Contacts
0   C:\ML Training Docs\New folder\data_final\NHSL...               NHSLA
0   C:\ML Training Docs\New folder\data_final\3rd ...    3rd Party Expert
0   C:\ML Training Docs\New folder\data_final\MDU ...        MDU Invoices
..                                                ...                 ...
0   C:\ML Training Docs\New folder\data_final\GMC\...                 GMC
0   C:\ML Training Docs\New folder\data_final\GMC\...                 GMC
0   C:\ML Training Docs\New folder\data_final\MDU ...        MDU Invoices
0   C:\ML Training Docs\New folder\data_final\NHSL...               NHSLA
0   C:\ML Training Docs\New folder\data_final\NHSL...               NHSLA

[2974 rows x 2 columns]

In [6]:
# data = pd.read_csv(r'C:\ML Training Docs\New folder\data1\my_data.csv')

In [33]:
# X_train=data.iloc[:,:1]
# y_train=data.iloc[:,-1:]

In [5]:
documents = []
nltk.set_proxy('http://Boopathi.Murugesan:Welcometothemdu2021@proxy.mdu.local:8080')
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

stemmer = WordNetLemmatizer()

for sen in range(0, len(X)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[sen]))
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)
    
    # Converting to Lowercase
    document = document.lower()
    
    # Lemmatization
    document = document.split()

    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\zz2839\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [6]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7)
X = vectorizer.fit_transform(documents).toarray()

In [7]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter = TfidfTransformer()
X = tfidfconverter.fit_transform(X).toarray()

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,shuffle=True)

In [9]:
'''training the data in RF model'''
from sklearn.ensemble._forest import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.8302521008403362


In [10]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
classifier=MultinomialNB()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.7445378151260504


In [11]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[122  15   4   0   0]
 [ 25 138   3   3   2]
 [  8  18  41   4   1]
 [  1   0   7 121   0]
 [ 17  35   4   5  21]]
              precision    recall  f1-score   support

           0       0.71      0.87      0.78       141
           1       0.67      0.81      0.73       171
           2       0.69      0.57      0.63        72
           3       0.91      0.94      0.92       129
           4       0.88      0.26      0.40        82

    accuracy                           0.74       595
   macro avg       0.77      0.69      0.69       595
weighted avg       0.76      0.74      0.73       595

0.7445378151260504


In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
classifier=DecisionTreeClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7260504201680672
[[100  19  10   1  11]
 [ 18 136   7   2   8]
 [  7  10  41   5   9]
 [  4   1   7 116   1]
 [ 13  11  19   0  39]]
              precision    recall  f1-score   support

           0       0.70      0.71      0.71       141
           1       0.77      0.80      0.78       171
           2       0.49      0.57      0.53        72
           3       0.94      0.90      0.92       129
           4       0.57      0.48      0.52        82

    accuracy                           0.73       595
   macro avg       0.69      0.69      0.69       595
weighted avg       0.73      0.73      0.73       595



In [13]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
classifier=GaussianNB()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6773109243697479
[[105   9   7   4  16]
 [ 24 103  21   5  18]
 [  5   8  40   6  13]
 [  4   1  16 107   1]
 [ 13  10   8   3  48]]
              precision    recall  f1-score   support

           0       0.70      0.74      0.72       141
           1       0.79      0.60      0.68       171
           2       0.43      0.56      0.49        72
           3       0.86      0.83      0.84       129
           4       0.50      0.59      0.54        82

    accuracy                           0.68       595
   macro avg       0.65      0.66      0.65       595
weighted avg       0.70      0.68      0.68       595



In [15]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
classifier=SVC()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print('SVC:',accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

SVC: 0.8369747899159664
[[125   7   6   0   3]
 [ 16 149   4   0   2]
 [  6  11  50   2   3]
 [  2   0   7 120   0]
 [ 15  10   2   1  54]]
              precision    recall  f1-score   support

           0       0.76      0.89      0.82       141
           1       0.84      0.87      0.86       171
           2       0.72      0.69      0.71        72
           3       0.98      0.93      0.95       129
           4       0.87      0.66      0.75        82

    accuracy                           0.84       595
   macro avg       0.84      0.81      0.82       595
weighted avg       0.84      0.84      0.84       595



In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
classifier=LogisticRegression()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print('LogisticRegression:',accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

LogisticRegression: 0.826890756302521
[[123   8   6   0   4]
 [ 14 149   3   1   4]
 [  5  16  47   1   3]
 [  1   0   7 121   0]
 [ 13  13   3   1  52]]
              precision    recall  f1-score   support

           0       0.79      0.87      0.83       141
           1       0.80      0.87      0.83       171
           2       0.71      0.65      0.68        72
           3       0.98      0.94      0.96       129
           4       0.83      0.63      0.72        82

    accuracy                           0.83       595
   macro avg       0.82      0.79      0.80       595
weighted avg       0.83      0.83      0.82       595



In [19]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
classifier=KNeighborsClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print('KNeighborsclassifier:',accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

KNeighborsclassifier: 0.7277310924369748
[[115  17   0   1   8]
 [ 25 137   0   0   9]
 [ 24  15  24   1   8]
 [  5   1   2 120   1]
 [ 27  16   0   2  37]]
              precision    recall  f1-score   support

           0       0.59      0.82      0.68       141
           1       0.74      0.80      0.77       171
           2       0.92      0.33      0.49        72
           3       0.97      0.93      0.95       129
           4       0.59      0.45      0.51        82

    accuracy                           0.73       595
   macro avg       0.76      0.67      0.68       595
weighted avg       0.75      0.73      0.72       595



In [20]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
classifier=SGDClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print('SGDClassifier:',accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

SGDClassifier: 0.8285714285714286
[[116   6   8   0  11]
 [  9 146   6   2   8]
 [  6   7  50   4   5]
 [  1   0   3 124   1]
 [ 11   9   4   1  57]]
              precision    recall  f1-score   support

           0       0.81      0.82      0.82       141
           1       0.87      0.85      0.86       171
           2       0.70      0.69      0.70        72
           3       0.95      0.96      0.95       129
           4       0.70      0.70      0.70        82

    accuracy                           0.83       595
   macro avg       0.81      0.81      0.81       595
weighted avg       0.83      0.83      0.83       595

